pipeline {
    agent {
        any {
            image 'maven:latest'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Maven') {
            steps {
                sh 'sudo apt-get install maven'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Delivers') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
